### ISSUE TITLE
Exception after a split second

### ISSUE THREAD

**Issue by jiink** [benaclejames/VRCFT-OSC-Receiver#1]
After selecting a mesh with all the shapekeys and starting the OSC server, it successfully receives a few frames of face tracking data from VRCFT. Then the addon quickly runs into this exception which causes it to stop:

```
Exception in thread Thread-19 (recv_and_process):
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.6\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Jacob\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\VRCFT OSC Receiver\osc_server.py", line 63, in recv_and_process
    process_osc_message(address, osc_data, standard)
  File "C:\Users\Jacob\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\VRCFT OSC Receiver\osc_server.py", line 43, in process_osc_message
    shape_key.value = osc_data
AttributeError: Writing to ID classes in this context is not allowed: Key.001, Key datablock, error setting ShapeKey.value
```

I tried 3 different models and the same thing happens, but "Key.001" in the exception may be "Key".

**Comment by benaclejames** [comment]
FIxed in latest
